### ISSUE TITLE
Undefined control sequence for Toks

### ISSUE THREAD

**Issue by liza-wood** [ryanpeek/aggiedown#6]
When knitting default template I get the following error:
```
! Undefined control sequence.
<argument> ...}}\NormalTok { pkg[}\SpecialCharTok 
                                                  {!}\NormalTok {(pkg }\Spec...
l.371 ...onTok{installed.packages}\NormalTok{())]}
```
The same [issue was raised by a user on a tex forum](https://tex.stackexchange.com/questions/660787/undefined-control-sequence-for-normaltok-or-specialchartok). Need to update Toks in the template ; @liza-wood will make pull request

**Comment by ryanpeek** [comment]
thanks for addressing with #14
